networks:
  # shared network for the assistant and webapp services
  gpt-assistant:
    driver: bridge

volumes:
  # shared volume for the assistant and webapp services to read/write log files
  logs:

services:
  assistant:
    container_name: gpt-assistant_assistant
    build:
      context: ./assistant # Builds the Docker image using the Dockerfile in the assistant directory
      dockerfile: ${ASSISTANT_DOCKERFILE:-Dockerfile} # Can overriide to specify dev version during development
    restart: unless-stopped
    privileged: true # Gives the container permission to access to hardware
    volumes:
      - ./assistant/src:/app/src # Mount source code for real-time updates in the container
      - ./assistant/package.json:/app/package.json # Mount package.json
      - ./assistant/package-lock.json:/app/package-lock.json # Mount package-lock.json
      - ./config.json:/app/config.json # Mount the config file
      - logs:/app/logs # Mount the logs volume
      - /etc/asound.conf:/etc/asound.conf # Audio config needed for audio to work
      - /dev/snd:/dev/snd # Gives access to the sound devices on the host machine
      - /dev/shm:/dev/shm # Hardware that needs to be mounted for audio to work
      - /usr/share/alsa:/usr/share/alsa # alsa is for handling audio in Linux
      - /var/run/dbus:/var/run/dbus # allows programs on the same machine to communicate with each other
    networks:
      - gpt-assistant
    tmpfs:
      - /run # Used to store temporary files that are deleted on reboot
      - /run/lock # Used for preventing concurrent access to resources
    stdin_open: true # Allows you to start an interactive session with the container
    tty: true # Allows terminal interaction
    command: ${ASSISTANT_COMMAND:-bash -c "node ./dist/main.js"} # Using bash allows SIGTERM to be caught and handled properly
  webapp:
    container_name: gpt-assistant_webapp
    build:
      context: ./webapp # Builds the Docker image using the Dockerfile in the webapp directory
      dockerfile: ${WEBAPP_DOCKERFILE:-Dockerfile} # Can overriide to specify dev version during development
    restart: unless-stopped
    volumes:
      - ./webapp/src:/app/src # Mount source code for real-time updates in the container
      - ./webapp/public:/app/public # Mount public directory
      - ./webapp/package.json:/app/package.json # Mount package.json
      - ./webapp/package-lock.json:/app/package-lock.json # Mount package-lock.json
      - ./config.json:/app/config.json # Mount the config file
      - logs:/app/logs # Mount the logs volume
      - /var/run/docker.sock:/var/run/docker.sock # Allows the webapp to communicate with the Docker daemon
    networks:
      - gpt-assistant
    ports:
      - "8900:3000" # Maps port 8900 on the host to port 3000 in the container
    stdin_open: true # Allows you to run commands interactively in the container. Ex: 'docker exec -it <container_id> bash'
    tty: true # Allows terminal interaction
    command: ${WEBAPP_COMMAND:-node server.js} #server.js is created by next build from standalone output: https://nextjs.org/docs/pages/api-reference/next-config-js/output
