services:
  gpt_assistant:
    build: . # Builds the Docker image using the Dockerfile in the current directory
    restart: unless-stopped
    privileged: true # Gives the container permission to access to hardware
    network_mode: host # Uses the host network stack for the container
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} # API key for the OpenAI API
      - PICOVOICE_ACCESS_KEY=${PICOVOICE_ACCESS_KEY} # Access key for the Picovoice SDK
      - VOLUME_CONTROL_DEVICE=${VOLUME_CONTROL_DEVICE} # The audio device to use for volume control
      - VOLUME_CONTROL_DEVICE_INDEX=${VOLUME_CONTROL_DEVICE_INDEX} # The index of the audio device to use for volume control
      - ADDRESS=${ADDRESS} # Address for weather information
      - TIMEZONE=${TIMEZONE}
      - GEOCODIO_API_KEY=${GEOCODIO_API_KEY} # API key for the Geocodio API for weather lookup
    volumes:
      - ~/gpt-assistant:/app # Mounts the local directory ~/gpt-assistant to /app in the container
      - /etc/asound.conf:/etc/asound.conf # Audio config needed for audio to work
      - /dev/snd:/dev/snd # Gives access to the sound devices on the host machine
      - /dev/shm:/dev/shm # Hardware that needs to be mounted for audio to work
      - /usr/share/alsa:/usr/share/alsa # alsa is for handling audio in Linux
      - /var/run/dbus:/var/run/dbus # allows programs on the same machine to communicate with each other
    tmpfs:
      - /run # Used to store temporary files that are deleted on reboot
      - /run/lock # Used for preventing concurrent access to resources
    stdin_open: true # Allows you to start an interactive session with the container
    tty: true # Allows terminal interaction
    command: bash # Overrides the default command and runs the bash shell
